# Generated by Django 5.0.7 on 2025-10-05 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_format', models.CharField(blank=True, max_length=20, null=True)),
                ('component_type', models.CharField(choices=[('audio', 'Audio'), ('visual', 'Visual'), ('graphics', 'Graphics'), ('text', 'Text/Typography'), ('effect', 'Effect'), ('transition', 'Transition'), ('overlay', 'Overlay'), ('configuration', 'Configuration')], max_length=20)),
            ],
            options={
                'verbose_name': 'Component',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyboard_shortcut', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_type', models.CharField(choices=[('keyboard', 'Keyboard Shortcut'), ('mouse', 'Mouse Tool'), ('software_feature', 'Software Feature'), ('plugin', 'Plugin/Extension'), ('hardware', 'Hardware Tool'), ('command', 'Command/Tool')], max_length=30)),
                ('software_platform', models.CharField(choices=[('premiere', 'Adobe Premiere Pro'), ('davinci', 'DaVinci Resolve'), ('audition', 'Adobe Audition'), ('after_effects', 'After Effects'), ('universal', 'Universal'), ('multiple', 'Multiple Platforms')], max_length=30)),
                ('category', models.CharField(choices=[('cutting', 'Cutting'), ('trimming', 'Trimming'), ('effects', 'Effects'), ('audio', 'Audio'), ('navigation', 'Navigation'), ('selection', 'Selection'), ('timeline', 'Timeline')], max_length=20)),
            ],
            options={
                'verbose_name': 'Tool',
                'ordering': ['software_platform', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_domains', to='database.domain')),
            ],
            options={
                'verbose_name': 'Sub Domain',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('file_path', 'File Path'), ('text_segment', 'Text Segment'), ('image', 'Image'), ('audio', 'Audio Clip'), ('video_clip', 'Video Clip'), ('tutorial', 'Tutorial')], max_length=20)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp_start', models.DurationField(blank=True, null=True)),
                ('timestamp_end', models.DurationField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('sub_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='database.subdomain')),
            ],
            options={
                'verbose_name': 'Reference',
                'ordering': ['-quality_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='database.subdomain')),
            ],
            options={
                'verbose_name': 'Phase',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='database.domain')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='database.phase')),
                ('sub_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='database.subdomain')),
            ],
            options={
                'verbose_name': 'Concept',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='database.concept')),
            ],
            options={
                'verbose_name': 'Theme',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Storytelling', 'Rhythm & timing (how editing communicates the story)'), ('rhythm_timing', 'Rhythm & timing (how it flows)'), ('transitions', 'Transitions (how shots connect)'), ('sound', 'Sound (what it feels like to hear)'), ('emotion_psychology', 'Emotion/psychology (how it makes you feel)'), ('visual_composition', 'Visual composition (what you look at)'), ('style_creativity', 'Style/creativity (what makes it unique)'), ('workflow', 'Workflow (how you efficiently execute)')], max_length=30)),
                ('outcome', models.TextField()),
                ('instructions', models.JSONField(default=list)),
                ('tools_used', models.JSONField(default=list)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('usage_frequency', models.IntegerField(default=0)),
                ('components', models.ManyToManyField(blank=True, related_name='techniques', to='database.component')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='database.phase')),
                ('references', models.ManyToManyField(blank=True, related_name='techniques', to='database.reference')),
                ('themes', models.ManyToManyField(blank=True, related_name='techniques', to='database.theme')),
                ('tools', models.ManyToManyField(blank=True, related_name='techniques', to='database.tool')),
            ],
            options={
                'verbose_name': 'Technique',
                'ordering': ['phase', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('components', models.ManyToManyField(blank=True, related_name='compositions', to='database.component')),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.concept')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.domain')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.phase')),
                ('references', models.ManyToManyField(blank=True, related_name='compositions', to='database.reference')),
                ('sub_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.subdomain')),
                ('technique', models.ManyToManyField(blank=True, related_name='compositions', to='database.technique')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.theme')),
                ('tools', models.ManyToManyField(blank=True, related_name='compositions', to='database.tool')),
            ],
            options={
                'verbose_name': 'Composition',
            },
        ),
    ]
