# Generated by Django 5.2.6 on 2025-09-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('youtube', 'YouTube'), ('social', 'social'), ('manual', 'Manual'), ('web', 'Web Doc'), ('spreadsheet', 'Spreadsheet'), ('file', 'User Uploaded File')], max_length=20)),
                ('source_identifier', models.CharField(max_length=255)),
                ('raw_content', models.TextField(blank=True, null=True)),
                ('processed_content', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contentsource',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='messagefeedback',
            name='message',
        ),
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept_name', models.CharField(max_length=255)),
                ('content_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.informationsource')),
                ('related_nodes', models.ManyToManyField(blank=True, to='database.knowledgenode')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.topic')),
            ],
            options={
                'verbose_name': 'Base Model',
                'verbose_name_plural': 'Base Models',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ContentMetadata',
        ),
        migrations.DeleteModel(
            name='ContentSource',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageFeedback',
        ),
    ]
