# Generated by Django 5.2.6 on 2025-09-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_informationsource_topic_userquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_format', models.CharField(blank=True, max_length=20, null=True)),
                ('component_type', models.CharField(choices=[('audio', 'Audio'), ('visual', 'Visual'), ('graphics', 'Graphics'), ('text', 'Text/Typography'), ('effect', 'Effect'), ('transition', 'Transition'), ('overlay', 'Overlay'), ('configuration', 'Configuration')])),
            ],
            options={
                'verbose_name': 'Component',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('components', models.ManyToManyField(blank=True, related_name='compositions', to='database.component')),
            ],
            options={
                'verbose_name': 'Composition',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concept',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Domain',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phase',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('file_path', 'File Path'), ('text_segment', 'Text Segment'), ('image', 'Image'), ('audio', 'Audio Clip'), ('video_clip', 'Video Clip'), ('tutorial', 'Tutorial')], max_length=20)),
                ('content_url', models.URLField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp_start', models.DurationField(blank=True, null=True)),
                ('timestamp_end', models.DurationField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('quality_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
            ],
            options={
                'verbose_name': 'Reference',
                'ordering': ['-quality_rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_domains', to='database.domain')),
            ],
            options={
                'verbose_name': 'Sub Domain',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Storytelling', 'Rhythm & timing (how editing communicates the story)'), ('rhythm_timing', 'Rhythm & timing (how it flows)'), ('transitions', 'Transitions (how shots connect)'), ('sound', 'Sound (what it feels like to hear)'), ('emotion_psychology', 'Emotion/psychology (how it makes you feel)'), ('visual_composition', 'Visual composition (what you look at)'), ('style_creativity', 'Style/creativity (what makes it unique)'), ('workflow', 'Workflow (how you efficiently execute)')])),
                ('outcome', models.TextField()),
                ('instructions', models.JSONField(default=list)),
                ('tools_used', models.JSONField(default=list)),
                ('estimated_time', models.DurationField(blank=True, null=True)),
                ('usage_frequency', models.IntegerField(default=0)),
                ('components', models.ManyToManyField(blank=True, related_name='techniques', to='database.component')),
            ],
            options={
                'verbose_name': 'Technique',
                'ordering': ['phase', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyboard_shortcut', models.CharField(blank=True, max_length=50, null=True)),
                ('tool_type', models.CharField(choices=[('keyboard', 'Keyboard Shortcut'), ('mouse', 'Mouse Tool'), ('software_feature', 'Software Feature'), ('plugin', 'Plugin/Extension'), ('hardware', 'Hardware Tool'), ('command', 'Command/Tool')])),
                ('software_platform', models.CharField(choices=[('premiere', 'Adobe Premiere Pro'), ('davinci', 'DaVinci Resolve'), ('audition', 'Adobe Audition'), ('after_effects', 'After Effects'), ('universal', 'Universal'), ('multiple', 'Multiple Platforms')])),
                ('category', models.CharField(choices=[('cutting', 'Cutting'), ('trimming', 'Trimming'), ('effects', 'Effects'), ('audio', 'Audio'), ('navigation', 'Navigation'), ('selection', 'Selection'), ('timeline', 'Timeline')])),
            ],
            options={
                'verbose_name': 'Tool',
                'ordering': ['software_platform', 'category', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='knowledgenode',
            name='content_source',
        ),
        migrations.RemoveField(
            model_name='knowledgenode',
            name='related_nodes',
        ),
        migrations.RemoveField(
            model_name='knowledgenode',
            name='topic',
        ),
        migrations.DeleteModel(
            name='UserQuestion',
        ),
        migrations.AddField(
            model_name='composition',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.concept'),
        ),
        migrations.AddField(
            model_name='concept',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='database.domain'),
        ),
        migrations.AddField(
            model_name='composition',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.domain'),
        ),
        migrations.AddField(
            model_name='concept',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='database.phase'),
        ),
        migrations.AddField(
            model_name='composition',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.phase'),
        ),
        migrations.AddField(
            model_name='composition',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='compositions', to='database.reference'),
        ),
        migrations.AddField(
            model_name='reference',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='database.subdomain'),
        ),
        migrations.AddField(
            model_name='phase',
            name='sub_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='database.subdomain'),
        ),
        migrations.AddField(
            model_name='concept',
            name='sub_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='database.subdomain'),
        ),
        migrations.AddField(
            model_name='composition',
            name='sub_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.subdomain'),
        ),
        migrations.AddField(
            model_name='technique',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='database.phase'),
        ),
        migrations.AddField(
            model_name='technique',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='techniques', to='database.reference'),
        ),
        migrations.AddField(
            model_name='composition',
            name='technique',
            field=models.ManyToManyField(blank=True, related_name='compositions', to='database.technique'),
        ),
        migrations.AddField(
            model_name='theme',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='database.concept'),
        ),
        migrations.AddField(
            model_name='technique',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='techniques', to='database.theme'),
        ),
        migrations.AddField(
            model_name='composition',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='database.theme'),
        ),
        migrations.AddField(
            model_name='technique',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='techniques', to='database.tool'),
        ),
        migrations.AddField(
            model_name='composition',
            name='tools',
            field=models.ManyToManyField(blank=True, related_name='compositions', to='database.tool'),
        ),
        migrations.DeleteModel(
            name='InformationSource',
        ),
        migrations.DeleteModel(
            name='KnowledgeNode',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
