# Generated by Django 5.2.6 on 2025-09-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_component_composition_concept_domain_phase_reference_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_domain_name'),
        ),
    ]
