# Generated by Django 5.2.6 on 2025-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_domain_unique_domain_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='domain',
            name='unique_domain_name',
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
