# Generated by Django 5.0.7 on 2025-10-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_url', models.URLField(max_length=500)),
                ('video_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'YouTube Transcript',
                'verbose_name_plural': 'YouTube Transcripts',
                'ordering': ['-created_at'],
            },
        ),
    ]
