# Generated by Django 5.0.7 on 2025-10-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetranscript',
            name='channel_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='youtubetranscript',
            name='transcript_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
