# Generated by Django 5.0.7 on 2025-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_youtubetranscript_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetranscript',
            name='transcript_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
