# Generated by Django 5.0.7 on 2025-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_youtubetranscript_transcript_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubetranscript',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubetranscript',
            name='transcript_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
