# Generated by Django 5.0.7 on 2025-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_alter_youtubetranscript_channel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebContentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('content_markdown', models.TextField()),
                ('content_html', models.TextField(blank=True, null=True)),
                ('extracted_json', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Web Content Source',
                'verbose_name_plural': 'Web Content Sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
